### PR TITLE
Add licenses directory with the appropriate percona licenses

### PR DESCRIPTION
**Pull request by jardon**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Docs update

* **What is the current behavior?** (You can also link to an open issue here)
Only the license for the snap package is included.

* **What is the new behavior (if this is a feature change)?**
Licenses for the snap, as well as the percona packages, are included.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
Nope

* **Other information**:
[percona-server-mongodb-license](https://github.com/percona/percona-server-mongodb/blob/master/LICENSE-Community.txt)
[percona-backup-mongodb-license](https://github.com/percona/percona-backup-mongodb/blob/main/LICENSE)

### CODE REVIEW

**Review by taurus-forever — COMMENTED** [review]
LGTM, but SNAP recently [received](https://github.com/canonical/charmed-mongodb-snap/commit/6c9ccb5b8562055014698a19f29c896f427d5f43) exporter, can you please add it's license here too. Tnx!

**Review by MiaAltieri — COMMENTED** [review]
Noob question - why do we have to include the licenses within the snap . Is it not suitable to reference them via link within the README or something like that?

**Review by MiaAltieri — APPROVED** [review]
Thank you!!

**Comment by taurus-forever** [comment]
> Noob question - why do we have to include the licenses within the snap . Is it not suitable to reference them via link within the README or something like that?

replied in rock: https://github.com/canonical/charmed-mongodb-rock/pull/15#issuecomment-1473412835

**Review by taurus-forever — APPROVED** [review]

**Pull request merged**
