### PR TITLE
fix ulimit

### PR DESCRIPTION
**Pull request by delgod**
recommended values https://www.mongodb.com/docs/manual/reference/ulimit/

### CODE REVIEW

**Comment by plars** [comment]
As mentioned on the matrix channel, I tried this patch applied to the "5" track (the one that I'm running) and confirmed that /proc/<pid>/limits shows 64000 for both the soft and the hard limits now - previously the hard limits were much higher, but not sure if that's really a concern - probably more of a concern that the soft limit was previously only 1024 I would guess.

I was wondering when we might expect something like this to roll out to the snaps so that we can update and see if it fixes our problems in production?

**Review by Mehdi-Bendriss — APPROVED** [review]
Thank you!

**Review by MiaAltieri — COMMENTED** [review]
This looks good , but QQ is it necessary for the other daemons (mongodb_exporter and PBM)?

**Comment by Mehdi-Bendriss** [comment]
@MiaAltieri  it does not seem like it (from their respective docs) - those ulimits are usually relevant for the DB itself

**Review by MiaAltieri — APPROVED** [review]
Excellent job - thank you!

**Pull request merged**
